# Generated by Django 4.2.15 on 2024-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_now',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
