# Generated by Django 4.2.15 on 2024-08-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_watch_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='main_cast',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='watch_now',
            new_name='trailer_watch_now',
        ),
    ]
